//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_TRAINING.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case_Basic
    {
        public string Estimate_Num { get; set; }
        public System.DateTime Send_Time { get; set; }
        public System.DateTime Complete_Time { get; set; }
        public bool Urgent_Flag { get; set; }
        public string Case_Num { get; set; }
        public string Send_Unit { get; set; }
        public string Send_Person { get; set; }
        public string Customer_Task { get; set; }
        public string Estimator { get; set; }
        public string Appraiser { get; set; }
        public string Other_Estimate_Cost { get; set; }
        public decimal Other_Cost { get; set; }
        public string Other_Cost_Type { get; set; }
        public string Other_Cost_Desc { get; set; }
        public decimal Total_Estimate_Cost { get; set; }
        public bool Land_Products_Flag { get; set; }
        public bool Builder_Products_Flag { get; set; }
        public string InputUser { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public bool Delete_Flag { get; set; }
        public string Delete_Desc { get; set; }
        public bool Out_Flag { get; set; }
        public System.Guid BankID { get; set; }
        public int Case_Type { get; set; }
        public int ProcessID { get; set; }
        public string Send_Unit_Branch { get; set; }
        public Nullable<System.Guid> ReportID { get; set; }
        public string Borrower { get; set; }
        public decimal Report_Cost { get; set; }
        public decimal Estimate_Cost_Percent { get; set; }
        public string Delete_Type { get; set; }
        public bool Is_Appeal { get; set; }
        public string Appeal_Type { get; set; }
        public Nullable<System.DateTime> Finally_Finish_Time { get; set; }
        public Nullable<System.DateTime> Delete_Time { get; set; }
        public string Delete_User { get; set; }
        public string Total_Reviewer { get; set; }
        public string Remark { get; set; }
    }
}
