//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_TRAINING.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case_Basic_Builder_Products
    {
        public string Estimate_Num { get; set; }
        public int BuilderID { get; set; }
        public string Builder_Number { get; set; }
        public string Community_Name { get; set; }
        public Nullable<int> Floor_Up { get; set; }
        public Nullable<int> Floor_Down { get; set; }
        public Nullable<decimal> House_Age { get; set; }
        public Nullable<decimal> Value_Add_Tax { get; set; }
        public Nullable<decimal> Land_Hold_Area { get; set; }
        public Nullable<decimal> Builder_Hold_Area { get; set; }
        public string InputUser { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string Lot_Number { get; set; }
        public string sFloor_Up { get; set; }
        public string sFloor_Down { get; set; }
    }
}
