//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_TRAINING.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case_Basic_Builder_Price_Detail
    {
        public string Estimate_Num { get; set; }
        public int BuilderPriceID { get; set; }
        public string Desc { get; set; }
        public Nullable<decimal> Hold_Area { get; set; }
        public Nullable<decimal> Unit_Price_L { get; set; }
        public Nullable<decimal> Unit_Price_H { get; set; }
        public string InputUser { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
