//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_TRAINING.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menus()
        {
            this.Roles_Menus = new HashSet<Roles_Menus>();
        }
    
        public System.Guid MenuID { get; set; }
        public string Menu_Name { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Menu_Url { get; set; }
        public Nullable<System.Guid> Menu_ParentID { get; set; }
        public string Icon { get; set; }
        public int Sort { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<bool> Type_Insert { get; set; }
        public Nullable<bool> Type_Update { get; set; }
        public Nullable<bool> Type_Delete { get; set; }
        public Nullable<bool> Type_Select { get; set; }
        public Nullable<bool> Type_Execue { get; set; }
        public Nullable<bool> Type_Report { get; set; }
        public Nullable<bool> Type_Spe1 { get; set; }
        public Nullable<bool> Type_Spe2 { get; set; }
        public Nullable<bool> Type_Spe3 { get; set; }
        public Nullable<bool> Type_Spe4 { get; set; }
        public string Name_Spe1 { get; set; }
        public string Name_Spe2 { get; set; }
        public string Name_Spe3 { get; set; }
        public string Name_Spe4 { get; set; }
        public Nullable<bool> Loading_Flag { get; set; }
        public string InputUser { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Roles_Menus> Roles_Menus { get; set; }
    }
}
