//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_TRAINING.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process_JumpReturn_History
    {
        public int Serial { get; set; }
        public string Estimate_Num { get; set; }
        public int ProcessID { get; set; }
        public int Changed_ProcessID { get; set; }
        public string Process_Return_Desc { get; set; }
        public string InputUser { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public int Case_Type { get; set; }
    }
}
