//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_TRAINING.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles_Menus
    {
        public System.Guid Serial { get; set; }
        public System.Guid RoleID { get; set; }
        public System.Guid MenuID { get; set; }
        public Nullable<bool> Type_Insert { get; set; }
        public Nullable<bool> Type_Update { get; set; }
        public Nullable<bool> Type_Delete { get; set; }
        public Nullable<bool> Type_Select { get; set; }
        public Nullable<bool> Type_Execue { get; set; }
        public Nullable<bool> Type_Report { get; set; }
        public bool Type_Spe1 { get; set; }
        public bool Type_Spe2 { get; set; }
        public bool Type_Spe3 { get; set; }
        public bool Type_Spe4 { get; set; }
        public string InputUser { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual Menus Menus { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
